# Quick Test Configuration for Reference Checker Ultra
# Purpose: Verify functionality with minimal processing time (3-5 files only)
project_base_path: "C:/EGOS"  # Absolute path to project base directory

# Only include specific subdirectories for testing
included_directories:
  - "scripts/cross_reference"  # Just the cross_reference directory for quick testing

# File types to check for references
file_types:
  - "*.py"     # Python files
  - "*.md"     # Markdown files
  - "*.yaml"   # YAML files
  - "*.yml"    # YAML files

# Directories to exclude from scanning
excluded_directories:
  - "**/venv/**"        # Virtual environments
  - "**/__pycache__/**" # Python cache
  - "**/node_modules/**" # Node.js modules
  - "**/build/**"        # Build directories
  - "**/dist/**"         # Distribution directories

# Files to exclude from scanning
excluded_files:
  - "**/*.pyc"          # Python compiled files
  - "**/*.pyo"          # Python optimized files
  - "**/*.pyd"          # Python dynamically loaded modules
  - "**/.DS_Store"      # macOS metadata
  - "**/Thumbs.db"      # Windows thumbnail cache
  - "**/.git/**"        # Git files

# Target files to find references to (only modified in last X days)
target_file_pattern:
  days_modified: 7      # Only files modified in the last week
  min_size_bytes: 100   # Minimum file size to consider
  max_size_mb: 5        # Maximum file size to consider (in MB)

# Performance settings
performance:
  max_workers: 2        # Limit workers for quick test
  batch_size: 5         # Process files in batches
  cache_enabled: true   # Use file content caching
  timeout_sec: 10       # Timeout for processing a single file
  quick_test: true      # Enable quick test mode (3-5 files only)
  avg_time_per_file_sec: 2.0  # Average time per file for quick test

# Scan parameters
scan_parameters:
  scan_directories: ["scripts/cross_reference"]  # Only scan cross_reference directory
  max_depth: 3          # Maximum directory depth to scan
  follow_symlinks: false # Whether to follow symbolic links
  min_similarity: 0.8   # Minimum similarity threshold for fuzzy matching

# Reference finding parameters
reference_finding:
  method: "auto"        # auto, python, or ripgrep
  max_line_length: 200  # Maximum line length to include in results
  include_context: true # Whether to include surrounding context
  timeout_sec: 10       # Timeout for processing a single file
  patterns: ["{filename}", "{module}", "{basename}"] # Patterns to search for

# Output settings
output:
  report_dir: "reports/cross_reference"  # Directory to save reports
  max_references_per_file: 100  # Maximum references to show per file
  console_detail_level: "normal"  # minimal, normal, or detailed

# Reporting configuration
reporting:
  format: "html"              # html, json, or markdown
  include_stats: true         # Include performance statistics
  include_visualization: true # Include visualizations
  report_path: "reports/cross_reference/report.html"  # Path for the main report
  summary_path: "reports/cross_reference/summary.md"  # Path for the summary report
  checkpoint_path: "reports/cross_reference/checkpoint_quick_test.json"  # Path for checkpoint file

# Experimental features
experimental:
  use_aho_corasick: true    # Use Aho-Corasick for multi-pattern matching
  use_ripgrep: false        # Use external ripgrep tool if available
