#!/usr/bin/env bun
/**
 * scripts/disseminate-propagator.ts — EGOS Kernel Propagator (DISS-002)
 *
 * Reads .egos-disseminate-manifest.json (generated by DISS-001 disseminate-scanner.ts),
 * then for each repo in existing_repos:
 *   1. Updates the `# EGOS-KERNEL-PROPAGATED: DATE` marker in CLAUDE.md and .windsurfrules
 *   2. Commits with `chore(kernel): propagate YYYY-MM-DD [N rules]`
 *
 * Usage:
 *   bun scripts/disseminate-propagator.ts [--dry] [--repo /path/to/repo]
 *   bun scripts/disseminate-propagator.ts --all     # propagate to all existing_repos
 *
 * Marker format expected in target files:
 *   # EGOS-KERNEL-PROPAGATED: YYYY-MM-DD
 *   <!-- AUTO-INJECTED ... -->
 *   (injected summary block)
 *   ---
 *
 * If marker not found, a new block is prepended to the file.
 */

import { execSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

// ── Config ──────────────────────────────────────────────────────────────────

const REPO_ROOT = resolve(dirname(import.meta.path), "..");
const MANIFEST_PATH = join(REPO_ROOT, ".egos-disseminate-manifest.json");
const DRY = process.argv.includes("--dry");
const ALL = process.argv.includes("--all");
const REPO_ARG = process.argv.find(a => a.startsWith("--repo="))?.replace("--repo=", "");

// Files to update inside each target repo
const TARGET_FILES = ["CLAUDE.md", ".windsurfrules"];

// Marker that identifies the auto-injected block
const MARKER_PREFIX = "# EGOS-KERNEL-PROPAGATED:";
const BLOCK_END = "---"; // end of injected block
const BLOCK_COMMENT = "<!-- AUTO-INJECTED by disseminate-propagator.ts — DO NOT EDIT THIS BLOCK MANUALLY -->";

// ── Types ───────────────────────────────────────────────────────────────────

interface ChangedRule {
  file: string;
  label: string;
  section: string;
  change_type: "added" | "modified" | "removed";
  diff_lines: number;
}

interface DisseminateManifest {
  date: string;
  commit: string;
  since_commit: string;
  changed_rules: ChangedRule[];
  affected_repos: string[];
  existing_repos: string[];
  propagation_needed: boolean;
  generated_at: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function loadManifest(): DisseminateManifest | null {
  if (!existsSync(MANIFEST_PATH)) {
    console.error(`[propagator] Manifest not found: ${MANIFEST_PATH}`);
    console.error(`[propagator] Run: bun scripts/disseminate-scanner.ts first`);
    return null;
  }
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf-8")) as DisseminateManifest;
}

function buildInjectedBlock(manifest: DisseminateManifest): string {
  const { date, commit, changed_rules } = manifest;
  const ruleCount = changed_rules.length;

  const ruleLines = changed_rules.slice(0, 10).map(r => {
    const icon = r.change_type === "added" ? "+" : r.change_type === "removed" ? "-" : "~";
    const section = r.section === "(preamble)" ? r.label : `${r.label} → ${r.section}`;
    return `<!-- ${icon} ${section} (${r.diff_lines} lines) -->`;
  });
  if (ruleCount > 10) ruleLines.push(`<!-- ... and ${ruleCount - 10} more -->`);

  return [
    `${MARKER_PREFIX} ${date}`,
    BLOCK_COMMENT,
    `<!-- Kernel commit: ${commit} | ${ruleCount} rule section(s) changed -->`,
    `<!-- Kernel rules: ~/.claude/CLAUDE.md (always authoritative) -->`,
    `<!-- Re-run: bun ~/egos/scripts/disseminate-propagator.ts --all to update -->`,
    ...ruleLines,
    ``,
    `> **EGOS Kernel rules apply to this repo.** See \`~/.claude/CLAUDE.md\` for full rules.`,
    `> Critical non-negotiables: no force-push main, no secret logging, no git add -A in agents.`,
    `> SSOT map: \`~/.claude/egos-rules/ssot-map.md\` | LLM routing: \`~/.claude/egos-rules/llm-routing.md\``,
    ``,
    BLOCK_END,
  ].join("\n");
}

/**
 * Update or insert the injected block in a file.
 * Returns true if file was modified.
 */
function updateFile(filePath: string, injectedBlock: string): boolean {
  if (!existsSync(filePath)) {
    console.log(`  [propagator] File not found, skipping: ${filePath}`);
    return false;
  }

  const content = readFileSync(filePath, "utf-8");
  const lines = content.split("\n");

  // Find existing marker
  const markerIdx = lines.findIndex(l => l.startsWith(MARKER_PREFIX));

  if (markerIdx === -1) {
    // No existing block — prepend
    const newContent = injectedBlock + "\n\n" + content;
    if (!DRY) writeFileSync(filePath, newContent);
    console.log(`  [propagator] + Prepended block to ${filePath.split("/").pop()}`);
    return true;
  }

  // Find end of existing block (first `---` after marker or next `#` heading)
  let blockEndIdx = markerIdx + 1;
  while (blockEndIdx < lines.length) {
    const line = lines[blockEndIdx];
    if (line === BLOCK_END || (line.startsWith("# ") && blockEndIdx > markerIdx + 2)) break;
    blockEndIdx++;
  }
  // Include the `---` line in replacement if it's the end marker
  if (lines[blockEndIdx] === BLOCK_END) blockEndIdx++;

  // Replace old block with new block
  const before = lines.slice(0, markerIdx);
  const after = lines.slice(blockEndIdx);
  const newContent = [...before, injectedBlock, ...after].join("\n");

  if (newContent === content) {
    console.log(`  [propagator] = No change needed: ${filePath.split("/").pop()}`);
    return false;
  }

  if (!DRY) writeFileSync(filePath, newContent);
  console.log(`  [propagator] ✓ Updated block in ${filePath.split("/").pop()}`);
  return true;
}

/**
 * Commit changes in a target repo.
 */
function commitRepo(repoPath: string, date: string, ruleCount: number): boolean {
  const result = spawnSync("git", [
    "-C", repoPath,
    "status", "--short"
  ], { encoding: "utf-8" });

  if (!result.stdout.trim()) {
    console.log(`  [propagator] No changes to commit in ${repoPath}`);
    return false;
  }

  const addResult = spawnSync("git", [
    "-C", repoPath,
    "add", "CLAUDE.md", ".windsurfrules"
  ], { encoding: "utf-8" });

  if (addResult.status !== 0) {
    console.error(`  [propagator] git add failed: ${addResult.stderr}`);
    return false;
  }

  const message = `chore(kernel): propagate ${date} [${ruleCount} rules]\n\nAuto-propagated from egos kernel by disseminate-propagator.ts (DISS-002).\nSource commit: see .egos-disseminate-manifest.json\n\nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>`;
  const commitResult = spawnSync("git", [
    "-C", repoPath,
    "commit", "-m", message,
    "--no-verify" // bypass hooks in target repos (not kernel)
  ], { encoding: "utf-8" });

  if (commitResult.status !== 0) {
    console.error(`  [propagator] git commit failed: ${commitResult.stderr}`);
    return false;
  }

  console.log(`  [propagator] ✅ Committed in ${repoPath.split("/").pop()}`);
  return true;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const manifest = loadManifest();
  if (!manifest) process.exit(1);

  if (!manifest.propagation_needed && !ALL) {
    console.log(`[propagator] No propagation needed (manifest says propagation_needed=false)`);
    console.log(`[propagator] Use --all to force propagation anyway`);
    process.exit(0);
  }

  console.log(`[propagator] Manifest: ${manifest.date} | commit ${manifest.commit} | ${manifest.changed_rules.length} rules changed`);
  console.log(`[propagator] Target repos: ${manifest.existing_repos.length}/${manifest.affected_repos.length} exist`);
  if (DRY) console.log(`[propagator] DRY RUN — no writes`);

  const injectedBlock = buildInjectedBlock(manifest);
  const repos = REPO_ARG ? [REPO_ARG] : manifest.existing_repos;

  let updated = 0;
  let committed = 0;
  let skipped = 0;

  for (const repoPath of repos) {
    if (!existsSync(repoPath)) {
      console.log(`[propagator] ⚠️  Repo not found: ${repoPath} — skipping`);
      skipped++;
      continue;
    }

    // Check it's a git repo
    const gitCheck = spawnSync("git", ["-C", repoPath, "rev-parse", "--git-dir"], { encoding: "utf-8" });
    if (gitCheck.status !== 0) {
      console.log(`[propagator] ⚠️  Not a git repo: ${repoPath} — skipping`);
      skipped++;
      continue;
    }

    console.log(`\n[propagator] → ${repoPath.split("/").pop()} (${repoPath})`);

    let repoModified = false;
    for (const targetFile of TARGET_FILES) {
      const filePath = join(repoPath, targetFile);
      if (updateFile(filePath, injectedBlock)) {
        repoModified = true;
        updated++;
      }
    }

    if (repoModified && !DRY) {
      if (commitRepo(repoPath, manifest.date, manifest.changed_rules.length)) {
        committed++;
      }
    }
  }

  console.log(`\n[propagator] Summary: ${updated} file(s) updated, ${committed} repo(s) committed, ${skipped} skipped`);
  if (DRY) console.log(`[propagator] Re-run without --dry to apply changes`);
}

main().catch(err => {
  console.error("[propagator] Fatal:", err);
  process.exit(1);
});
