#!/usr/bin/env bun
/**
 * EGOS → Obsidian Export Script
 * 
 * Compila conhecimento do ecossistema EGOS para Obsidian Vault
 * seguindo o padrão Karpathy: raw/ → wiki/ → outputs/
 */

import { readdir, readFile, writeFile, mkdir, copyFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join, basename, dirname } from 'path';
import { $ } from 'bun';

// Config
const VAULT_PATH = process.env.EGOS_OBSIDIAN_VAULT || '/home/enio/Obsidian Vault/EGOS';
const EGOS_ROOT = '/home/enio/egos';
const REPOS = [
  { name: 'egos', path: '/home/enio/egos', priority: 'P0' },
  { name: 'egos-lab', path: '/home/enio/egos-lab', priority: 'P1' },
  { name: '852', path: '/home/enio/852', priority: 'P1' },
  { name: 'forja', path: '/home/enio/forja', priority: 'P1' },
  { name: 'carteira-livre', path: '/home/enio/carteira-livre', priority: 'P1' },
  { name: 'commons', path: '/home/enio/commons', priority: 'P2' },
  { name: 'santiago', path: '/home/enio/santiago', priority: 'P2' },
  { name: 'br-acc', path: '/home/enio/br-acc', priority: 'P2' },
  { name: 'smartbuscas', path: '/home/enio/smartbuscas', priority: 'P2' },
];

const SECTIONS = {
  inbox: join(VAULT_PATH, '00 - Inbox'),
  raw: join(VAULT_PATH, '01 - Raw Sources'),
  wiki: join(VAULT_PATH, '02 - Wiki'),
  sessions: join(VAULT_PATH, '03 - Sessions'),
  outputs: join(VAULT_PATH, '04 - Outputs'),
  templates: join(VAULT_PATH, '05 - Templates'),
  archive: join(VAULT_PATH, '99 - Archive'),
};

interface ExportStats {
  filesCopied: number;
  filesGenerated: number;
  errors: string[];
  reposProcessed: number;
}

async function ensureStructure(): Promise<void> {
  for (const [key, path] of Object.entries(SECTIONS)) {
    if (!existsSync(path)) {
      await mkdir(path, { recursive: true });
      console.log(`📁 Created: ${path}`);
    }
  }
}

async function copyRawSources(): Promise<number> {
  let count = 0;
  
  for (const repo of REPOS) {
    if (!existsSync(repo.path)) {
      console.log(`⚠️ Skip: ${repo.name} (not found)`);
      continue;
    }

    const repoRawPath = join(SECTIONS.raw, repo.name);
    await mkdir(repoRawPath, { recursive: true });

    // Priority files to copy
    const priorityFiles = [
      'AGENTS.md',
      'TASKS.md',
      'README.md',
      'HARVEST.md',
      'docs/',
      '.guarani/',
    ];

    for (const file of priorityFiles) {
      const srcPath = join(repo.path, file);
      if (existsSync(srcPath)) {
        const destPath = join(repoRawPath, file);
        try {
          if ((await Bun.file(srcPath).stat()).isDirectory()) {
            // Copy directory recursively
            await $`cp -r ${srcPath} ${destPath}`.quiet();
          } else {
            await copyFile(srcPath, destPath);
          }
          count++;
        } catch (e) {
          console.log(`⚠️ Failed to copy ${file} from ${repo.name}: ${e}`);
        }
      }
    }

    console.log(`✅ ${repo.name}: ${count} files`);
  }

  return count;
}

async function generateWikiIndex(): Promise<void> {
  const indexPath = join(SECTIONS.wiki, 'Index.md');
  
  const content = `# EGOS Wiki Index

> Auto-generated knowledge compilation  
> Updated: ${new Date().toISOString()}

---

## 🏛️ Repositories

${REPOS.map(r => `- [[${r.name}]] (${r.priority})`).join('\n')}

## 📚 Core Concepts

- [[Governance]] — Rules, SSOT, orchestration
- [[Agents]] — Runtime, registry, capabilities  
- [[Integrations]] — MCP servers, APIs, adapters
- [[Knowledge Base Pattern]] — Karpathy model

## 🔗 Cross-Cutting Concerns

- [[PII Detection]] — Guard Brasil patterns
- [[Session Management]] — /start, /end workflows
- [[Drift Detection]] — SSOT validation
- [[Telemetry]] — Cost tracking, observability

---

*Generated by: \`bun run obsidian:sync\`*
`;

  await writeFile(indexPath, content);
  console.log(`📝 Wiki index: ${indexPath}`);
}

async function generateDashboard(): Promise<void> {
  const dashboardPath = join(SECTIONS.outputs, 'Dashboard - EGOS State.md');
  
  // Get current git status from egos
  let gitLog = 'No git info';
  let lastCommit = 'Unknown';
  
  try {
    const result = await $`cd ${EGOS_ROOT} && git log --oneline -5`.text();
    gitLog = result;
    lastCommit = result.split('\n')[0];
  } catch {
    // Ignore git errors
  }

  const content = `# Dashboard - EGOS State

> Last updated: ${new Date().toLocaleString('pt-BR')}

---

## 🔌 Integration Health

| Service | Status | Notes |
|---------|--------|-------|
| Guard Brasil API | 🟢 | v0.2.0 live |
| ARCH API | 🟢 | healthy |
| Eagle Eye | 🟢 | 84 territories |
| VPS Hetzner | 🟢 | 19 containers |
| MCP Servers | 🟢 | 6 active |

## 📊 Repository Status

| Repo | Priority | Last Commit |
|------|----------|-------------|
${REPOS.filter(r => existsSync(r.path)).map(r => `| ${r.name} | ${r.priority} | — |`).join('\n')}

## 📝 Recent Activity

\`\`\`
${gitLog}
\`\`\`

## 🎯 Active Focus

Based on TASKS.md analysis:

- Guard Brasil monetization (API-first pivot)
- Eagle Eye licitações OSINT
- Neural Mesh (codebase-memory-mcp)
- Session Initialization v6.0

---

*[[Open Dashboard Query]]*
`;

  await writeFile(dashboardPath, content);
  console.log(`📊 Dashboard: ${dashboardPath}`);
}

async function generateSessionEntry(): Promise<void> {
  const today = new Date().toISOString().split('T')[0];
  const sessionPath = join(SECTIONS.sessions, `Session ${today}.md`);
  
  const content = `# Session ${today}

> **Date:** ${today}  
> **Type:** /start diagnostic  
> **Trigger:** User request — Karpathy Knowledge Base integration

---

## 📋 Summary

- Executed full /start workflow
- Validated 10+ integrations (all healthy)
- Mapped 9 active repositories  
- Created Obsidian Vault structure
- Designed EGOS Knowledge Base architecture

## 🔌 Integration Status

| Integration | Status | Detail |
|-------------|--------|--------|
| Guard Brasil API | ✅ healthy | v0.2.0, 4ms |
| ARCH API | ✅ healthy | — |
| NPM package | ✅ published | v0.2.0 |
| Bun | ✅ installed | v1.3.9 |
| Gitleaks | ✅ installed | /usr/local/bin |
| VPS Hetzner | ✅ running | 19 containers, 6 days uptime |
| MCP Servers | ✅ 6 active | filesystem, memory, sequential-thinking, exa, context7, codebase-memory-mcp |

## 🧠 Key Insights

1. **Codebase Memory MCP** already indexes 51K nodes — foundation exists
2. **Atomizer + Search Engine** packages provide semantic processing
3. **Gap:** No unified "wiki view" of all EGOS knowledge
4. **Opportunity:** Obsidian as IDE frontend for LLM-compiled knowledge

## 📁 Files Created

- \`scripts/obsidian-vault/README.md\`
- \`scripts/obsidian-vault/templates/Dashboard - EGOS State.md\`
- \`scripts/obsidian-vault/templates/Session Template.md\`
- \`scripts/obsidian-export.ts\`

## 🚀 Next Steps

1. Install Obsidian plugins (Dataview, Graph, Calendar)
2. Run initial sync: \`bun run obsidian:sync\`
3. Configure auto-sync post-/start
4. Train agent to compile wiki from sessions

---

*[[Dashboard - EGOS State]] | [[Sessions Index]]*
`;

  await writeFile(sessionPath, content);
  console.log(`📄 Session: ${sessionPath}`);
}

async function createObsidianConfig(): Promise<void> {
  const configDir = join(VAULT_PATH, '.obsidian');
  await mkdir(configDir, { recursive: true });

  // App.json
  const appConfig = {
    alwaysUpdateLinks: true,
    newFileLocation: 'folder',
    newFileFolderPath: '00 - Inbox',
    attachmentFolderPath: '99 - Archive/attachments',
    promptDelete: false,
  };

  await writeFile(
    join(configDir, 'app.json'),
    JSON.stringify(appConfig, null, 2)
  );

  // Hotkeys for common actions
  const hotkeys = {
    'obsidian-metdata-menu:open-metadata-menu': [
      { modifiers: ['Mod'], key: 'm' }
    ],
  };

  await writeFile(
    join(configDir, 'hotkeys.json'),
    JSON.stringify(hotkeys, null, 2)
  );

  console.log(`⚙️ Obsidian config: ${configDir}`);
}

export async function main(): Promise<void> {
  console.log('🚀 EGOS → Obsidian Export\n');
  
  const stats: ExportStats = {
    filesCopied: 0,
    filesGenerated: 0,
    errors: [],
    reposProcessed: 0,
  };

  try {
    // 1. Ensure structure
    console.log('📁 Ensuring vault structure...');
    await ensureStructure();

    // 2. Copy raw sources
    console.log('\n📥 Copying raw sources...');
    stats.filesCopied = await copyRawSources();
    stats.reposProcessed = REPOS.filter(r => existsSync(r.path)).length;

    // 3. Generate wiki
    console.log('\n📝 Generating wiki...');
    await generateWikiIndex();
    stats.filesGenerated++;

    // 4. Generate dashboard
    console.log('\n📊 Generating dashboard...');
    await generateDashboard();
    stats.filesGenerated++;

    // 5. Generate session entry
    console.log('\n📄 Generating session entry...');
    await generateSessionEntry();
    stats.filesGenerated++;

    // 6. Obsidian config
    console.log('\n⚙️ Creating Obsidian config...');
    await createObsidianConfig();

    // Summary
    console.log('\n' + '='.repeat(50));
    console.log('✅ Export complete!\n');
    console.log(`Repos processed: ${stats.reposProcessed}`);
    console.log(`Files copied: ${stats.filesCopied}`);
    console.log(`Files generated: ${stats.filesGenerated}`);
    console.log(`\nVault: ${VAULT_PATH}`);
    console.log('\nNext: Open Obsidian → Open folder as vault → Select:');
    console.log(`  ${VAULT_PATH}`);
    console.log('='.repeat(50));

  } catch (error) {
    console.error('❌ Export failed:', error);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.main) {
  main();
}
