#!/usr/bin/env bun
/**
 * pr:pack — generate a ready-to-paste PR message with environment notes,
 * validation slots and signed-off footer.
 *
 * Usage:
 *   bun scripts/pr-pack.ts --title "[AREA] change" --out /tmp/pr.md
 *   bun scripts/pr-pack.ts --title "[AREA] change" --dry
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { execSync } from 'child_process';

interface Options {
  title: string;
  out?: string;
  dry: boolean;
}

function argValue(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return undefined;
  return process.argv[idx + 1];
}

function parseOptions(): Options {
  const title = argValue('--title')?.trim();
  if (!title) {
    console.error('Missing required --title argument');
    process.exit(1);
  }

  return {
    title,
    out: argValue('--out'),
    dry: process.argv.includes('--dry'),
  };
}

function run(cmd: string): string {
  return execSync(cmd, { encoding: 'utf-8' }).trim();
}

function safeRun(cmd: string): string {
  try {
    return run(cmd);
  } catch {
    return 'unavailable';
  }
}

function getChangedFiles(): string[] {
  const output = safeRun('git diff --name-only --cached');
  if (output === 'unavailable' || output.length === 0) return [];
  return output.split('\n').map((s) => s.trim()).filter(Boolean);
}

function detectKernelPath(): string {
  if (process.env.EGOS_KERNEL?.trim()) return process.env.EGOS_KERNEL;
  return '/root/egos';
}

function governanceCheckHint(): string {
  const kernelPath = detectKernelPath();
  return `If governance scripts fail, rerun with EGOS_KERNEL=${kernelPath === '/root/egos' ? '/workspace/egos (container default)' : kernelPath}`;
}

function loadTemplate(): string {
  const templatePath = resolve('.github/pull_request_template.md');
  if (!existsSync(templatePath)) {
    return '# Summary\n- [ ] Fill details\n\nSigned-off-by: EGOS Codex Agent <codex@egos.local>\n';
  }
  const template = readFileSync(templatePath, 'utf-8');
  if (template.includes('Signed-off-by:')) return template;
  return `${template.trimEnd()}\n\nSigned-off-by: EGOS Codex Agent <codex@egos.local>\n`;
}

function nextTasks(limit = 5): string[] {
  const tasksPath = resolve('TASKS.md');
  if (!existsSync(tasksPath)) return [];

  const content = readFileSync(tasksPath, 'utf-8');
  const matches = content
    .split('\n')
    .filter((line) => line.startsWith('- [ ] EGOS-'))
    .slice(0, limit)
    .map((line) => line.replace('- [ ] ', '').trim());

  return matches;
}

function render(options: Options): string {
  const branch = safeRun('git rev-parse --abbrev-ref HEAD');
  const commit = safeRun('git rev-parse --short HEAD');
  const root = safeRun('git rev-parse --show-toplevel');
  const runtime = safeRun('bun --version');
  const changed = getChangedFiles();
  const backlog = nextTasks(6);
  const list = changed.length > 0
    ? changed.map((file) => `- [ ] ${file}`).join('\n')
    : '- [ ] (no staged files detected)';
  const nextTaskList = backlog.length > 0
    ? backlog.map((task) => `- [ ] ${task}`).join('\n')
    : '- [ ] (no open EGOS tasks found)';

  const template = loadTemplate();

  return [
    `<!-- Generated by scripts/pr-pack.ts -->`,
    `## PR Title`,
    options.title,
    '',
    `## Runtime Snapshot`,
    `- Branch: ${branch}`,
    `- Base commit: ${commit}`,
    `- Repo root: ${root}`,
    `- Bun: ${runtime}`,
    `- ${governanceCheckHint()}`,
    '',
    `## Changed Files (staged)`,
    list,
    '',
    `## Next Tasks (from TASKS.md)`,
    nextTaskList,
    '',
    `## Manual IDE Validation Required`,
    `- [ ] Run full local validation in Windsurf IDE.`,
    `- [ ] Run full local validation in Antigravity IDE.`,
    `- [ ] Confirm command outputs and screenshots where applicable.`,
    `- [ ] Re-run tests after any IDE-assisted edits.`,
    '',
    `## Template`,
    template,
  ].join('\n');
}

function main(): void {
  const options = parseOptions();
  const markdown = render(options);

  if (options.dry || !options.out) {
    console.log(markdown);
    return;
  }

  const outputPath = resolve(options.out);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, markdown, 'utf-8');
  console.log(`PR pack written to: ${outputPath}`);
}

main();
