#!/usr/bin/env bash
# ============================================================================
# scripts/session-aggregator.sh — Daily Session Handoff Generator
# ============================================================================
# Runs daily at 02:30 UTC (23:30 BRT). Produces one handoff file per day.
# Replaces manual /end on days where the user forgets.
#
# Usage:
#   bash scripts/session-aggregator.sh            # today's handoff
#   bash scripts/session-aggregator.sh --dry      # preview, no writes
#   AUTO_COMMIT=1 bash scripts/session-aggregator.sh  # commit + push
#
# Output: docs/_current_handoffs/handoff_YYYY-MM-DD.md
# Never overwrites an existing handoff (manual /end takes precedence).
# ============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HANDOFFS_DIR="$REPO_ROOT/docs/_current_handoffs"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
OUTPUT="$HANDOFFS_DIR/handoff_${DATE}.md"
DRY="${1:-}"

mkdir -p "$HANDOFFS_DIR"

# Guard: don't overwrite a manually-created handoff
if [ -f "$OUTPUT" ] && [ "$DRY" != "--dry" ]; then
  echo "[session-aggregator] handoff for $DATE already exists (manual /end took precedence)"
  echo "  path: $OUTPUT"
  exit 0
fi

# ── Data collection ──────────────────────────────────────────────────────────

# Today's commits
COMMITS=$(git -C "$REPO_ROOT" log \
  --since="${DATE} 00:00:00" \
  --until="${DATE} 23:59:59" \
  --format="- \`%h\` %s" 2>/dev/null || echo "_no commits today_")
COMMIT_COUNT=$(git -C "$REPO_ROOT" log \
  --since="${DATE} 00:00:00" \
  --until="${DATE} 23:59:59" \
  --oneline 2>/dev/null | wc -l | tr -d ' ')

# Tasks completed today (marked ✅ YYYY-MM-DD by auto-disseminate)
TASKS_DONE=$(grep "✅ ${DATE}" "$REPO_ROOT/TASKS.md" 2>/dev/null | wc -l | tr -d ' ')

# Total active tasks (unchecked)
TASKS_ACTIVE=$(grep "^- \[ \]" "$REPO_ROOT/TASKS.md" 2>/dev/null | wc -l | tr -d ' ')

# Files changed today (unique)
FILES_CHANGED=$(git -C "$REPO_ROOT" log \
  --since="${DATE} 00:00:00" \
  --name-only \
  --format="" 2>/dev/null | sort -u | grep -v '^$' | head -20 || echo "_none_")

# CCR job CRITICAL alerts (last 3 days)
CRITICALS=$(grep -r "CRITICAL\|🔴" "$REPO_ROOT/docs/jobs/" \
  --include="*.md" --include="*.json" -l 2>/dev/null \
  | xargs -I{} basename {} 2>/dev/null \
  | head -5 || echo "none")

# Latest governance drift (non-zero = alert)
GOV_DRIFT=""
if [ -f "$REPO_ROOT/docs/jobs/doc-drift-cron.log" ]; then
  GOV_DRIFT=$(tail -5 "$REPO_ROOT/docs/jobs/doc-drift-cron.log" 2>/dev/null \
    | grep -iE "DRIFT|FAIL|ERROR|CRIT" | head -3 || echo "")
fi

# P0 tasks
P0_TASKS=$(grep -A1 "P0\|🔴" "$REPO_ROOT/TASKS.md" 2>/dev/null \
  | grep "^- \[ \]" | head -5 || echo "_none_")

# ── Output ───────────────────────────────────────────────────────────────────

CONTENT="# Handoff — ${DATE}
> Auto-generated by scripts/session-aggregator.sh at ${TIME} UTC
> To add context: edit this file, then commit with: \`chore(handoff): annotate ${DATE}\`

---

## Session Metrics

| Metric | Value |
|--------|-------|
| Commits today | ${COMMIT_COUNT} |
| Tasks completed | ${TASKS_DONE} |
| Tasks active | ${TASKS_ACTIVE} |

---

## Today's Commits

${COMMITS}

---

## Files Changed

\`\`\`
${FILES_CHANGED}
\`\`\`

---

## P0 Blockers (still open)

${P0_TASKS}

---

## CCR Job Alerts

Files with CRITICAL/🔴 markers:
${CRITICALS}

$([ -n "$GOV_DRIFT" ] && echo "Governance drift log:" && echo "\`\`\`" && echo "$GOV_DRIFT" && echo "\`\`\`" || true)

---

## Next Session Checklist

- [ ] Read: \`TASKS.md\` P0s and P1s
- [ ] Check: \`docs/jobs/\` for overnight CCR reports
- [ ] VPS: \`ssh root@204.168.217.125 \"systemctl status hermes-gateway\"\`
- [ ] Hermes: token still valid? Check \`/tmp/hermes-token-refresh.log\`
- [ ] Revenue: did we advance GTM today? (post / conversation / demo)

---
_Generated automatically — edit to add session context that matters_
"

if [ "$DRY" = "--dry" ]; then
  echo "[session-aggregator] DRY RUN — would write to: $OUTPUT"
  echo "---"
  echo "$CONTENT"
  exit 0
fi

echo "$CONTENT" > "$OUTPUT"
echo "[session-aggregator] handoff written: $OUTPUT"

# Auto-commit if requested (cron mode)
if [ "${AUTO_COMMIT:-0}" = "1" ]; then
  git -C "$REPO_ROOT" add "$OUTPUT"
  git -C "$REPO_ROOT" commit -m "chore(handoff): auto-generated daily handoff ${DATE}

[skip ci]" --no-verify 2>/dev/null || echo "[session-aggregator] nothing to commit"
  bash "$REPO_ROOT/scripts/safe-push.sh" 2>/dev/null \
    || echo "[session-aggregator] push failed (non-fatal)"
  echo "[session-aggregator] committed and pushed"
fi

exit 0
