/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EGOSLLMPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings-ui.ts
var import_obsidian = require("obsidian");
var EGOSLLMSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "EGOS LLM Connector Settings" });
    new import_obsidian.Setting(containerEl).setName("Default Provider").setDesc("Select the default LLM provider for commands").addDropdown((dropdown) => {
      dropdown.addOption("alibaba", "Alibaba DashScope (Qwen)").addOption("claude", "Claude (Anthropic)").addOption("codex", "Codex (OpenAI)").setValue(this.plugin.settings.defaultProvider).onChange(async (value) => {
        this.plugin.settings.defaultProvider = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Alibaba DashScope (Qwen)" });
    new import_obsidian.Setting(containerEl).setName("Enable Alibaba").setDesc("Enable Alibaba DashScope API").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.alibabaEnabled).onChange(async (value) => {
        this.plugin.settings.alibabaEnabled = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your Alibaba DashScope API Key (starts with sk-)").addText((text) => {
      text.setPlaceholder("sk-xxxxx").setValue(this.plugin.settings.alibabaApiKey).onChange(async (value) => {
        this.plugin.settings.alibabaApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Model").setDesc("Select Qwen model").addDropdown((dropdown) => {
      dropdown.addOption("qwen-plus", "Qwen Plus (recommended)").addOption("qwen-max", "Qwen Max").addOption("qwen-turbo", "Qwen Turbo").addOption("qwen-coder-plus", "Qwen Coder Plus").setValue(this.plugin.settings.alibabaModel).onChange(async (value) => {
        this.plugin.settings.alibabaModel = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Claude (Anthropic)" });
    new import_obsidian.Setting(containerEl).setName("Enable Claude").setDesc("Enable Claude API").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.claudeEnabled).onChange(async (value) => {
        this.plugin.settings.claudeEnabled = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your Anthropic API Key").addText((text) => {
      text.setPlaceholder("sk-ant-xxxxx").setValue(this.plugin.settings.claudeApiKey).onChange(async (value) => {
        this.plugin.settings.claudeApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Model").setDesc("Select Claude model").addDropdown((dropdown) => {
      dropdown.addOption("claude-3-7-sonnet-20250219", "Claude 3.7 Sonnet").addOption("claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet").addOption("claude-3-opus-20240229", "Claude 3 Opus").addOption("claude-3-5-haiku-20241022", "Claude 3.5 Haiku").setValue(this.plugin.settings.claudeModel).onChange(async (value) => {
        this.plugin.settings.claudeModel = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Codex (OpenAI)" });
    new import_obsidian.Setting(containerEl).setName("Enable Codex").setDesc("Enable Codex CLI integration (opens browser for auth)").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.codexEnabled).onChange(async (value) => {
        this.plugin.settings.codexEnabled = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Session Token").setDesc("Codex session token (auto-populated after browser login)").addText((text) => {
      text.setPlaceholder("auto-generated").setValue(this.plugin.settings.codexSessionToken).onChange(async (value) => {
        this.plugin.settings.codexSessionToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.setDisabled(true);
    });
    const codexNote = containerEl.createEl("div");
    codexNote.createEl("p", {
      text: 'To authenticate Codex: Open command palette \u2192 "EGOS LLM Connector: Login to Codex (Browser)"',
      cls: "setting-item-description"
    });
    codexNote.style.marginTop = "10px";
    codexNote.style.color = "var(--text-muted)";
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "Help & Links" });
    const helpDiv = containerEl.createEl("div");
    helpDiv.style.marginTop = "10px";
    helpDiv.createEl("a", {
      text: "Get Alibaba API Key \u2192",
      href: "https://dashscope.console.aliyun.com/apiKey"
    });
    helpDiv.createEl("br");
    helpDiv.createEl("a", {
      text: "Get Claude API Key \u2192",
      href: "https://console.anthropic.com/settings/keys"
    });
    helpDiv.createEl("br");
    helpDiv.createEl("a", {
      text: "Codex Documentation \u2192",
      href: "https://github.com/openai/codex"
    });
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  defaultProvider: "alibaba",
  alibabaEnabled: true,
  alibabaApiKey: "",
  alibabaModel: "qwen-plus",
  alibabaBaseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  claudeEnabled: false,
  claudeApiKey: "",
  claudeModel: "claude-3-7-sonnet-20250219",
  claudeBaseUrl: "https://api.anthropic.com/v1",
  codexEnabled: false,
  codexSessionToken: "",
  codexRefreshToken: ""
};

// src/llm-providers/alibaba.ts
var AlibabaProvider = class {
  constructor(settings) {
    this.name = "Alibaba";
    this.settings = settings;
  }
  isAvailable() {
    return this.settings.alibabaEnabled && !!this.settings.alibabaApiKey;
  }
  async chat(messages, options) {
    var _a, _b, _c, _d;
    const response = await fetch(`${this.settings.alibabaBaseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.alibabaApiKey}`
      },
      body: JSON.stringify({
        model: this.settings.alibabaModel,
        messages,
        temperature: (_a = options == null ? void 0 : options.temperature) != null ? _a : 0.7,
        max_tokens: (_b = options == null ? void 0 : options.maxTokens) != null ? _b : 2048,
        stream: false
      })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Alibaba API error: ${response.status} - ${error}`);
    }
    const data = await response.json();
    return ((_d = (_c = data.choices[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) || "";
  }
  async *streamChat(messages, options) {
    var _a, _b, _c, _d, _e, _f;
    const response = await fetch(`${this.settings.alibabaBaseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.alibabaApiKey}`
      },
      body: JSON.stringify({
        model: this.settings.alibabaModel,
        messages,
        temperature: (_a = options == null ? void 0 : options.temperature) != null ? _a : 0.7,
        max_tokens: (_b = options == null ? void 0 : options.maxTokens) != null ? _b : 2048,
        stream: true
      })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Alibaba API error: ${response.status} - ${error}`);
    }
    const reader = (_c = response.body) == null ? void 0 : _c.getReader();
    if (!reader)
      throw new Error("No response body");
    const decoder = new TextDecoder();
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done)
        break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (line.trim().startsWith("data: ")) {
          const data = line.trim().slice(6);
          if (data === "[DONE]")
            return;
          try {
            const parsed = JSON.parse(data);
            const content = (_f = (_e = (_d = parsed.choices) == null ? void 0 : _d[0]) == null ? void 0 : _e.delta) == null ? void 0 : _f.content;
            if (content)
              yield content;
          } catch (e) {
          }
        }
      }
    }
  }
};

// src/llm-providers/claude.ts
var ClaudeProvider = class {
  constructor(settings) {
    this.name = "Claude";
    this.settings = settings;
  }
  isAvailable() {
    return this.settings.claudeEnabled && !!this.settings.claudeApiKey;
  }
  async chat(messages, options) {
    var _a, _b, _c, _d;
    const systemMessage = messages.find((m) => m.role === "system");
    const conversationMessages = messages.filter((m) => m.role !== "system");
    const response = await fetch(`${this.settings.claudeBaseUrl}/messages`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.settings.claudeApiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.settings.claudeModel,
        max_tokens: (_a = options == null ? void 0 : options.maxTokens) != null ? _a : 4096,
        temperature: (_b = options == null ? void 0 : options.temperature) != null ? _b : 0.7,
        system: systemMessage == null ? void 0 : systemMessage.content,
        messages: conversationMessages.map((m) => ({
          role: m.role === "assistant" ? "assistant" : "user",
          content: m.content
        }))
      })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Claude API error: ${response.status} - ${error}`);
    }
    const data = await response.json();
    return ((_d = (_c = data.content) == null ? void 0 : _c[0]) == null ? void 0 : _d.text) || "";
  }
  async *streamChat(messages, options) {
    var _a, _b, _c, _d;
    const systemMessage = messages.find((m) => m.role === "system");
    const conversationMessages = messages.filter((m) => m.role !== "system");
    const response = await fetch(`${this.settings.claudeBaseUrl}/messages`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.settings.claudeApiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.settings.claudeModel,
        max_tokens: (_a = options == null ? void 0 : options.maxTokens) != null ? _a : 4096,
        temperature: (_b = options == null ? void 0 : options.temperature) != null ? _b : 0.7,
        system: systemMessage == null ? void 0 : systemMessage.content,
        messages: conversationMessages.map((m) => ({
          role: m.role === "assistant" ? "assistant" : "user",
          content: m.content
        })),
        stream: true
      })
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Claude API error: ${response.status} - ${error}`);
    }
    const reader = (_c = response.body) == null ? void 0 : _c.getReader();
    if (!reader)
      throw new Error("No response body");
    const decoder = new TextDecoder();
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done)
        break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (line.startsWith("data: ")) {
          const data = line.slice(6);
          if (data === "[DONE]")
            return;
          try {
            const event = JSON.parse(data);
            if (event.type === "content_block_delta" && ((_d = event.delta) == null ? void 0 : _d.text)) {
              yield event.delta.text;
            }
          } catch (e) {
          }
        }
      }
    }
  }
};

// src/llm-providers/codex.ts
var import_obsidian2 = require("obsidian");
var CodexProvider = class {
  constructor(settings) {
    this.name = "Codex";
    this.authServer = "https://auth.openai.com";
    this.apiServer = "https://api.openai.com";
    this.clientId = "codex-cli";
    this.redirectUri = "http://localhost:8080/callback";
    this.settings = settings;
  }
  isAvailable() {
    return this.settings.codexEnabled && !!this.settings.codexSessionToken;
  }
  async authenticate() {
    const codeVerifier = this.generateCodeVerifier();
    const codeChallenge = await this.generateCodeChallenge(codeVerifier);
    const state = this.generateState();
    const authUrl = new URL(`${this.authServer}/authorize`);
    authUrl.searchParams.set("client_id", this.clientId);
    authUrl.searchParams.set("response_type", "code");
    authUrl.searchParams.set("redirect_uri", this.redirectUri);
    authUrl.searchParams.set("code_challenge", codeChallenge);
    authUrl.searchParams.set("code_challenge_method", "S256");
    authUrl.searchParams.set("state", state);
    authUrl.searchParams.set("scope", "openid profile email api.read api.write");
    window.open(authUrl.toString(), "_blank");
    new import_obsidian2.Notice("Browser opened for Codex authentication. Complete login and paste the code here.");
    const code = await this.promptForAuthCode();
    if (!code) {
      throw new Error("Authentication cancelled");
    }
    await this.exchangeCodeForTokens(code, codeVerifier);
  }
  generateCodeVerifier() {
    const array = new Uint8Array(32);
    crypto.getRandomValues(array);
    return btoa(String.fromCharCode(...array)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
  }
  async generateCodeChallenge(verifier) {
    const encoder = new TextEncoder();
    const data = encoder.encode(verifier);
    const digest = await crypto.subtle.digest("SHA-256", data);
    return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
  }
  generateState() {
    const array = new Uint8Array(16);
    crypto.getRandomValues(array);
    return btoa(String.fromCharCode(...array));
  }
  async promptForAuthCode() {
    return new Promise((resolve) => {
      const modal = document.createElement("div");
      modal.className = "modal-container";
      modal.innerHTML = `
        <div class="modal">
          <div class="modal-content">
            <h3>Codex Authentication</h3>
            <p>After logging in the browser, paste the authorization code here:</p>
            <input type="text" id="auth-code" placeholder="Enter code..." style="width: 100%; margin: 10px 0;">
            <div class="modal-button-container">
              <button id="confirm-btn">Confirm</button>
              <button id="cancel-btn">Cancel</button>
            </div>
          </div>
        </div>
      `;
      document.body.appendChild(modal);
      const input = modal.querySelector("#auth-code");
      const confirmBtn = modal.querySelector("#confirm-btn");
      const cancelBtn = modal.querySelector("#cancel-btn");
      confirmBtn.addEventListener("click", () => {
        document.body.removeChild(modal);
        resolve(input.value);
      });
      cancelBtn.addEventListener("click", () => {
        document.body.removeChild(modal);
        resolve(null);
      });
      input.focus();
    });
  }
  async exchangeCodeForTokens(code, codeVerifier) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.authServer}/token`,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        client_id: this.clientId,
        code,
        code_verifier: codeVerifier,
        redirect_uri: this.redirectUri
      }).toString()
    });
    if (response.status !== 200) {
      throw new Error(`Token exchange failed: ${response.text}`);
    }
    const data = JSON.parse(response.text);
    this.settings.codexSessionToken = data.access_token;
    this.settings.codexRefreshToken = data.refresh_token;
    new import_obsidian2.Notice("Codex authentication successful!");
  }
  async chat(messages, options) {
    var _a, _b, _c, _d;
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.apiServer}/v1/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.codexSessionToken}`
      },
      body: JSON.stringify({
        model: "o3-mini",
        // Codex default model
        messages,
        temperature: (_a = options == null ? void 0 : options.temperature) != null ? _a : 0.7,
        max_tokens: (_b = options == null ? void 0 : options.maxTokens) != null ? _b : 4096
      })
    });
    if (response.status !== 200) {
      throw new Error(`Codex API error: ${response.status} - ${response.text}`);
    }
    const data = JSON.parse(response.text);
    return ((_d = (_c = data.choices[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) || "";
  }
  async refreshToken() {
    if (!this.settings.codexRefreshToken) {
      throw new Error("No refresh token available");
    }
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.authServer}/token`,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: new URLSearchParams({
        grant_type: "refresh_token",
        client_id: this.clientId,
        refresh_token: this.settings.codexRefreshToken
      }).toString()
    });
    if (response.status !== 200) {
      throw new Error(`Token refresh failed: ${response.text}`);
    }
    const data = JSON.parse(response.text);
    this.settings.codexSessionToken = data.access_token;
    if (data.refresh_token) {
      this.settings.codexRefreshToken = data.refresh_token;
    }
  }
};

// src/ui/chat-panel.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_CHAT = "egos-llm-chat";
var ChatPanel = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.currentProvider = "";
    this.plugin = plugin;
    this.currentProvider = plugin.settings.defaultProvider;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "EGOS LLM Chat";
  }
  getIcon() {
    return "egos-llm";
  }
  async onOpen() {
    this.containerEl.empty();
    this.render();
  }
  render() {
    const container = this.containerEl.createEl("div", { cls: "egos-chat-container" });
    container.style.height = "100%";
    container.style.display = "flex";
    container.style.flexDirection = "column";
    const header = container.createEl("div", { cls: "egos-chat-header" });
    header.style.padding = "10px";
    header.style.borderBottom = "1px solid var(--background-modifier-border)";
    header.style.display = "flex";
    header.style.gap = "10px";
    header.style.alignItems = "center";
    header.createEl("span", { text: "Provider:" });
    const providerSelect = header.createEl("select");
    const providers = [
      { value: "alibaba", label: "Alibaba (Qwen)" },
      { value: "claude", label: "Claude" },
      { value: "codex", label: "Codex" }
    ];
    providers.forEach((p) => {
      const option = providerSelect.createEl("option", { text: p.label, value: p.value });
      if (p.value === this.currentProvider) {
        option.selected = true;
      }
    });
    providerSelect.addEventListener("change", (e) => {
      this.currentProvider = e.target.value;
    });
    const clearBtn = header.createEl("button", { text: "Clear" });
    clearBtn.style.marginLeft = "auto";
    clearBtn.addEventListener("click", () => {
      this.messages = [];
      this.renderMessages();
    });
    const messagesArea = container.createEl("div", { cls: "egos-chat-messages" });
    messagesArea.style.flex = "1";
    messagesArea.style.overflow = "auto";
    messagesArea.style.padding = "10px";
    this.messagesArea = messagesArea;
    const inputArea = container.createEl("div", { cls: "egos-chat-input-area" });
    inputArea.style.padding = "10px";
    inputArea.style.borderTop = "1px solid var(--background-modifier-border)";
    inputArea.style.display = "flex";
    inputArea.style.gap = "10px";
    const input = inputArea.createEl("textarea", {
      cls: "egos-chat-input",
      attr: { placeholder: "Type your message...", rows: "3" }
    });
    input.style.flex = "1";
    input.style.resize = "none";
    const sendBtn = inputArea.createEl("button", { text: "Send", cls: "mod-cta" });
    sendBtn.addEventListener("click", () => this.sendMessage(input));
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && e.ctrlKey) {
        this.sendMessage(input);
      }
    });
    const contextBtn = inputArea.createEl("button", { text: "Add Note" });
    contextBtn.addEventListener("click", () => this.addCurrentNoteContext(input));
    this.renderMessages();
  }
  renderMessages() {
    this.messagesArea.empty();
    this.messages.forEach((msg) => {
      const msgEl = this.messagesArea.createEl("div", {
        cls: `egos-chat-message egos-chat-message-${msg.role}`
      });
      msgEl.style.marginBottom = "10px";
      msgEl.style.padding = "8px 12px";
      msgEl.style.borderRadius = "8px";
      msgEl.style.maxWidth = "85%";
      if (msg.role === "user") {
        msgEl.style.backgroundColor = "var(--interactive-accent)";
        msgEl.style.color = "var(--text-on-accent)";
        msgEl.style.marginLeft = "auto";
      } else {
        msgEl.style.backgroundColor = "var(--background-secondary)";
      }
      const content = msgEl.createEl("div");
      content.innerHTML = this.formatMessage(msg.content);
    });
    this.messagesArea.scrollTop = this.messagesArea.scrollHeight;
  }
  formatMessage(content) {
    return content.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/```(\w+)?\n([\s\S]*?)```/g, "<pre><code>$2</code></pre>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>").replace(/\n/g, "<br>");
  }
  async sendMessage(input) {
    const content = input.value.trim();
    if (!content)
      return;
    const provider = this.plugin.getProvider(this.currentProvider);
    if (!provider) {
      new import_obsidian3.Notice(`${this.currentProvider} not configured. Check settings.`);
      return;
    }
    this.messages.push({ role: "user", content });
    input.value = "";
    this.renderMessages();
    const typingEl = this.messagesArea.createEl("div", {
      text: "Thinking...",
      cls: "egos-chat-typing"
    });
    typingEl.style.fontStyle = "italic";
    typingEl.style.color = "var(--text-muted)";
    this.messagesArea.scrollTop = this.messagesArea.scrollHeight;
    try {
      const response = await provider.chat(this.messages);
      typingEl.remove();
      this.messages.push({ role: "assistant", content: response });
      this.renderMessages();
    } catch (error) {
      typingEl.remove();
      new import_obsidian3.Notice(`Error: ${error.message}`);
      this.messages.push({
        role: "assistant",
        content: `Error: ${error.message}`
      });
      this.renderMessages();
    }
  }
  async addCurrentNoteContext(input) {
    const activeFile = this.plugin.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian3.Notice("No active note");
      return;
    }
    try {
      const content = await this.plugin.app.vault.read(activeFile);
      const context = `

[Context from "${activeFile.name}"]:
${content.substring(0, 2e3)}${content.length > 2e3 ? "..." : ""}`;
      input.value += context;
      new import_obsidian3.Notice(`Added context from ${activeFile.name}`);
    } catch (error) {
      new import_obsidian3.Notice(`Error reading file: ${error.message}`);
    }
  }
  async onClose() {
  }
};

// src/main.ts
var EGOSLLMPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.providers = /* @__PURE__ */ new Map();
    this.chatPanel = null;
  }
  async onload() {
    await this.loadSettings();
    this.initializeProviders();
    (0, import_obsidian4.addIcon)("egos-llm", `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M12 2L2 7l10 5 10-5-10-5z"/>
      <path d="M2 17l10 5 10-5"/>
      <path d="M2 12l10 5 10-5"/>
    </svg>`);
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => {
        this.chatPanel = new ChatPanel(leaf, this);
        return this.chatPanel;
      }
    );
    this.addRibbonIcon("egos-llm", "EGOS LLM Chat", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "open-egos-llm-chat",
      name: "Open LLM Chat",
      callback: () => {
        this.activateChatView();
      }
    });
    this.addCommand({
      id: "ask-alibaba",
      name: "Ask Alibaba (Qwen)",
      callback: () => {
        this.quickAsk("alibaba");
      }
    });
    this.addCommand({
      id: "ask-claude",
      name: "Ask Claude",
      callback: () => {
        this.quickAsk("claude");
      }
    });
    this.addCommand({
      id: "ask-codex",
      name: "Ask Codex",
      callback: () => {
        this.quickAsk("codex");
      }
    });
    this.addCommand({
      id: "summarize-note",
      name: "Summarize Current Note",
      editorCallback: (editor, view) => {
        this.summarizeNote(editor, view);
      }
    });
    this.addCommand({
      id: "generate-tags",
      name: "Generate Tags for Note",
      editorCallback: (editor, view) => {
        this.generateTags(editor, view);
      }
    });
    this.addCommand({
      id: "login-codex",
      name: "Login to Codex (Browser)",
      callback: () => {
        this.loginCodex();
      }
    });
    this.addSettingTab(new EGOSLLMSettingTab(this.app, this));
    console.log("EGOS LLM Connector loaded");
  }
  onunload() {
    console.log("EGOS LLM Connector unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.initializeProviders();
  }
  initializeProviders() {
    this.providers.clear();
    if (this.settings.alibabaEnabled && this.settings.alibabaApiKey) {
      this.providers.set("alibaba", new AlibabaProvider(this.settings));
    }
    if (this.settings.claudeEnabled && this.settings.claudeApiKey) {
      this.providers.set("claude", new ClaudeProvider(this.settings));
    }
    if (this.settings.codexEnabled) {
      this.providers.set("codex", new CodexProvider(this.settings));
    }
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async quickAsk(providerName) {
    const provider = this.providers.get(providerName);
    if (!provider) {
      new import_obsidian4.Notice(`${providerName} not configured. Check settings.`);
      return;
    }
    new QuickAskModal(this.app, provider, providerName).open();
  }
  async summarizeNote(editor, view) {
    const content = editor.getValue();
    const provider = this.getDefaultProvider();
    if (!provider) {
      new import_obsidian4.Notice("No LLM provider configured");
      return;
    }
    new import_obsidian4.Notice("Summarizing...");
    try {
      const messages = [
        { role: "system", content: "Summarize the following note concisely:" },
        { role: "user", content }
      ];
      const response = await provider.chat(messages);
      editor.setCursor({ line: 0, ch: 0 });
      editor.replaceSelection(`> **Summary:** ${response}

`);
      new import_obsidian4.Notice("Summary added!");
    } catch (error) {
      new import_obsidian4.Notice(`Error: ${error.message}`);
    }
  }
  async generateTags(editor, view) {
    const content = editor.getValue();
    const provider = this.getDefaultProvider();
    if (!provider) {
      new import_obsidian4.Notice("No LLM provider configured");
      return;
    }
    new import_obsidian4.Notice("Generating tags...");
    try {
      const messages = [
        { role: "system", content: "Generate 3-5 relevant tags for this note. Return only the tags separated by commas, no explanation." },
        { role: "user", content: content.substring(0, 2e3) }
      ];
      const response = await provider.chat(messages);
      const tags = response.split(",").map((t) => t.trim()).filter((t) => t);
      const tagString = tags.map((t) => `#${t.replace(/\s+/g, "-")}`).join(" ");
      editor.replaceSelection(`

---
Tags: ${tagString}`);
      new import_obsidian4.Notice(`Tags: ${tags.join(", ")}`);
    } catch (error) {
      new import_obsidian4.Notice(`Error: ${error.message}`);
    }
  }
  async loginCodex() {
    const codexProvider = this.providers.get("codex");
    if (!codexProvider) {
      new import_obsidian4.Notice("Codex not enabled in settings");
      return;
    }
    await codexProvider.authenticate();
  }
  getDefaultProvider() {
    if (this.settings.defaultProvider && this.providers.has(this.settings.defaultProvider)) {
      return this.providers.get(this.settings.defaultProvider);
    }
    return this.providers.values().next().value;
  }
  getProvider(name) {
    return this.providers.get(name);
  }
};
var QuickAskModal = class extends import_obsidian4.Modal {
  constructor(app, provider, providerName) {
    super(app);
    this.provider = provider;
    this.providerName = providerName;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: `Ask ${this.providerName}` });
    const input = contentEl.createEl("textarea", {
      attr: { placeholder: "Enter your question...", rows: 4 }
    });
    input.style.width = "100%";
    const button = contentEl.createEl("button", { text: "Send" });
    button.style.marginTop = "10px";
    const responseDiv = contentEl.createEl("div");
    responseDiv.style.marginTop = "20px";
    responseDiv.style.whiteSpace = "pre-wrap";
    button.addEventListener("click", async () => {
      const question = input.value;
      if (!question)
        return;
      button.disabled = true;
      button.textContent = "Thinking...";
      try {
        const messages = [
          { role: "user", content: question }
        ];
        const response = await this.provider.chat(messages);
        responseDiv.textContent = response;
      } catch (error) {
        responseDiv.textContent = `Error: ${error.message}`;
      } finally {
        button.disabled = false;
        button.textContent = "Send";
      }
    });
    contentEl.createEl("button", { text: "Close" }).addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
