name: AutoCrossRef CI

on:
  pull_request:
    paths:
      - 'subsystems/AutoCrossRef/**'
      - '.github/workflows/autocrossref_ci.yml'
  push:
    branches: [main]
    paths:
      - 'subsystems/AutoCrossRef/**'
      - '.github/workflows/autocrossref_ci.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio
      
      - name: Run tests
        run: pytest -q subsystems/AutoCrossRef/tests