name: Python Linting (Ruff)

on:
  push:
    branches: [ "main", "develop" ] # Ajuste os branches conforme necessário
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Use a versão Python do seu projeto

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff Linter
      run: |
        ruff check .

    - name: Run Ruff Formatter Check
      run: |
        ruff format --check .